config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    match 'projects/' => 'projects#index', :via => [:get], :defaults => { :format => 'json' }
    get 'projects/index'
  end

  namespace :api do
    match 'todo/' => 'todo#index', :via => [:get], :defaults => { :format => 'json' }
    get 'todo/index'
    post 'todo/create' => 'todo#create'
    patch 'todo/update/:id' => 'todo#update'
  end

  get 'todo/index'

  patch 'todo/update/:id', to: 'todo#update', as: 'todo_update'

  post 'todo/create'

  root 'todo#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :todos, dependent: :destroy
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  def index
    respond_to do |format|
      format.json { render json: Project.all}
    end
  end
end

app/controllers/api/todo_controller.rb
class Api::TodoController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    respond_to do |format|
      format.json { render json: Todo.all.sort_by{ |e| e[:id]}}
    end
  end

  def create
    json = JSON.parse(request.body.read)
    @todo = Todo.create(json)
  end

  def update
    json = JSON.parse(request.body.read)

    @todo = Todo.find(params[:id])
    @todo.update(json)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
  def index
    @projects = Project.all
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(is_completed: !@todo.is_completed)
    redirect_back(fallback_location: root_path)
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.is_completed = false
    @todo.save
    redirect_back(fallback_location: root_path)
  end

  private def todo_params
    params.require(:todo).permit(:text, :is_completed, :project_id)
  end
end

app/helpers/api/projects_helper.rb
module Api::ProjectsHelper
end

app/helpers/api/todo_helper.rb
module Api::TodoHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true  %>
    <%= stylesheet_link_tag "application" %>

</head>

<body>
    <%= yield %>
</body>

</html>

app/views/todo/index.html.erb
<header>
  <div class="header-content">
    <div></div>
    <h1>Задачи</h1>
    <%= link_to(image_tag(image_path('addTodoIcon.png')), '#', id: 'showTodo-btn') %>
  </div>
</header>

<main>
  <div class="container-fluid">
    <% @projects.each do |project| %>
      <div class="col-sm-12 col-md-6 col-lg-4">
        <div class="card">
          <h2><%= project.title %></h2>
          <ul>
            <% project.todos.sort_by{ |e| e[:id]}.each do |todo| %>
              <li>
                <%= form_for(todo, method: 'patch', url: todo_update_path(todo.id)) do |f|%>
                  <%= f.check_box(:is_completed, {id: "todo-cb-#{todo.id}"}, true, false) %>
                  <%= f.label(:is_completed, todo.text, {for: "todo-cb-#{todo.id}", class: todo.is_completed ? 'checked' : nil}) %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</main>

<div class="modal" id="newTodo">
  <div class="modal-body">
    <div class="modal-header">
      <h2>Новая задача</h2>
    </div>
    <div class="modal-content">
      <%= form_for(:todo, url: todo_create_path, html: { id: 'newTodo-form' }) do |f| %>
        <div class="modal-inputs">
          <%= f.text_field(:text, { placeholder: 'Название задачи...' }) %>
          <%= f.select(:project_id, @projects.map { |p| [p.title, p.id] }, id: 'dropdown' ) %>
        </div>
        <div class="modal-buttons">
          <%= link_to('ОТМЕНА', '#', { id: 'discard-btn', style: 'background-color: #9F9F9F;'}) %>
          <%= link_to('OK', '#', id: 'submit-btn') %>
        </div>
      <% end %>
    </div>
  </div>
</div>